# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js 18 image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available) for npm install
COPY package.json ./

# Install npm dependencies
RUN npm install

# Bundle app source
COPY . .

# Environment variables to be set at runtime
ENV KINTONE_DOMAIN=[あなたが使用するサブドメイン].cybozu.com
ENV KINTONE_USERNAME=MCP接続で使用するkintoneユーザー名
ENV KINTONE_PASSWORD=kintoneユーザーのパスワード（平文）

# Expose any necessary ports (example: 8080)
# EXPOSE 8080

# Command to run the app
CMD ["node", "server.js"]
